[package]
name = "incydecy"
version = "0.2.0"
authors = ["Jack Arthur Harrhy <me@jackharrhy.com>"]
edition = "2024"

[dependencies]
dotenvy = "0.15.7"
serenity = "0.12.4"
tokio = { version = "1.47.1", features = ["full"] }
