[package]
name = "incydecy"
version = "0.1.0"
authors = ["Jack Arthur Harrhy <me@jackharrhy.com>"]
edition = "2018"

[dependencies]
env_logger = "0.6"
log = "0.4"
unic-emoji-char = "0.9.0"
redis = "0.11.0"
kankyo = "0.3.0"
serenity = "0.8"
regex = "1.2"
